### ISSUE TITLE
cfform xmlformat

### ISSUE THREAD

**Issue by jmohler1970** [AndrewKralovec/ColdFusion2018AsynExample#1]
I am not familiar with

```
<cfform name="asyncForm" 
    format="XML" 
    skin="basiccss"
```

Is that necessary for the demo, or is it just to make the form look nice?

**Comment by AndrewKralovec** [comment]
@jmohler1970 , Those `cfform` attributes are not necessary for the demo. Those attributes just add styling. You can read more about those attributes [here ](https://helpx.adobe.com/coldfusion/developing-applications/requesting-and-presenting-information/creating-skinnable-xml-forms/building-xml-skinnable-forms.html).
